- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install packages requested by customer
      apt:
        name:
          - gparted
          - gedit
          - git
          - python3
          - ansible
          - ca-certificates
          - openssh-server
          - minicom
          - d-feet
          - fping
        state: present
        update_cache: yes

    - import_tasks: docker.yml
    - import_tasks: secure-root.yml
